services:
  postgres:
    image: postgres:18
    container_name: postgres_keycloak
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: super_secret_password
    ports:
      - "5432:5432"
    healthcheck: # it should be ready before keycloak starts
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak_server
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: super_secret_password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin@123
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        # Document about service_healthy here: https://docs.docker.com/compose/how-tos/startup-order/
        condition: service_healthy

volumes:
  postgres_data: